version: '3.8'

services:
  storage:
    build: ./STORAGE
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/eversun

  api:
    build: ./API
    ports:
      - "3000:3000"
    depends_on:
      - mqtt

  mqtt:
    build: ./MQTT
    depends_on:
      - storage

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./WEB
    ports:
      - "8080:80"

volumes:
  mongo-data:
